OCPBUGS-4090: swift: Retry connecting to OpenStack
openshift/cluster-image-registry-operator pull request #819
Opened 2022-11-25 15:17 UTC by pierreprinetti

The function IsSwiftEnabled probes a connection to Swift to determine whether CIRO should fall back to using a persistent volume claim as a storage backend. This function runs on the OpenStack platform to provide an alternative solution for when Swift is not available.

Before this patch, any failure to communicate with Swift would make CIRO fall back to using a PVC. However, a failure to probing Swift could come from a temporary failure to reach the OpenStack API.

With this patch, when an issue with the connection to the OpenStack identity service is not allowing CIRO to probe Swift, the probing is restarted for a maximum of five minutes.

As a consequence, after this patch, temporary failures in early steps of the connection to Swift, do not make CIRO fall back to using persistent volume claims when object storage is available in OpenStack.

2022-11-25 15:19 UTC, pierreprinetti commented
/jira refresh

2022-11-25 15:51 UTC, flavianmissi commented
/lgtm

2022-11-25 16:01 UTC, pierreprinetti commented
/hold
just to have at least another openstack review. Thanks

2022-11-25 16:38 UTC, EmilienM commented
/lgtm

2022-11-25 16:39 UTC, pierreprinetti commented
Cool, thanks. I'll just wait for `e2e-openstack` to complete successfully before removing the hold.

2022-11-25 17:02 UTC, mdbooth requested changes
This doesn't look right to me for a couple of reasons. Firstly implementing a backoff loop inside a reconciler generally isn't the right thing to do because it will (depending on the implementation, at least) prevent the reconciler from doing anything else. The idiomatic thing to do is to return an error and wait to be called again.

Secondly, we have enough context in [getSwitchClient](https://github.com/openshift/cluster-image-registry-operator/blob/d975b6524f7957e8a7332650b85e541d59a246b0/pkg/storage/swift/swift.go#L280-L286) to know if the error is that swift isn't installed in the cluster, in which case we should fallback immediately, or that swift just isn't working right now, in which case we should never fallback.

2022-11-27 16:26 UTC, pierreprinetti commented
/retest

2022-11-29 08:54 UTC, flavianmissi commented
@pierreprinetti please address @mdbooth's feedback - I think it makes sense. I'll hold approval for now.
/approve cancel

2022-11-29 10:44 UTC, pierreprinetti commented
@flavianmissi sure, I will address Matt's comment. Note that this bug is important for us, but not urgent; I had to put it aside for a moment.

2022-12-17 02:43 UTC, pierreprinetti commented
/retest

2022-12-18 21:45 UTC, pierreprinetti commented
/retest

2022-12-18 21:50 UTC, pierreprinetti commented
> The idiomatic thing to do is to return an error and wait to be called again.

Thank you. The function now errors.

> Secondly, we have enough context in [getSwitchClient](https://github.com/openshift/cluster-image-registry-operator/blob/d975b6524f7957e8a7332650b85e541d59a246b0/pkg/storage/swift/swift.go#L280-L286) to know if the error is that swift isn't installed in the cloud, in which case we should fallback immediately, or that swift just isn't working right now, in which case we should never fallback.

The current logic also falls back to Cinder in case of insufficient permissions (for example, the user does not have the Swift role). Unless I am missing something, this means that we have to probe directly acting on Swift.

PTAL!

2022-12-18 21:51 UTC, pierreprinetti commented
/hold cancel

2022-12-19 13:10 UTC, flavianmissi commented
/retest

2022-12-19 15:48 UTC, flavianmissi commented
Leaving LGTM to OpenStack folks.
/approve

2022-12-21 18:15 UTC, pierreprinetti commented
/retest-required

2022-12-21 21:46 UTC, pierreprinetti commented
/retest-required

2022-12-22 09:03 UTC, pierreprinetti commented
/retest-required

2022-12-22 13:26 UTC, mandre reviewed
/lgtm

2022-12-22 13:26 UTC, mandre commented on pkg/storage/swift/swift.go
> +			// In gophercloud the default endpoint type for
Thanks for adding the documentation to the code, to spare some git spelunking for the next person trying to understand what this code is about.

2022-12-22 13:30 UTC, merged

2022-12-22 15:57 UTC, pierreprinetti commented
/cherry-pick release-4.12